name: tracker_x
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  # background_fetch:
  #   git:
  #     url: https://github.com/transistorsoft/flutter_background_fetch
  cloud_firestore: ^6.0.0
  connectivity_plus: ^6.1.5
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_map: ^8.2.1
  font_awesome_flutter: ^10.9.0
  geofencing_api: ^2.0.0
  geolocator: ^14.0.2
  google_fonts: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.5.0
  hydrated_bloc: ^10.1.1
  latlong2: ^0.9.1
  path_provider: ^2.1.5
  uuid: ^4.5.1
  workmanager: ^0.9.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/
